export { default as Table } from './Table.vue'
export { default as TableHeader } from './TableHead.vue'
export { default as TableHead } from './TableHeadCell.vue'
export { default as TableBody } from './TableBody.vue'
export { default as TableRow } from './TableRow.vue'
export { default as TableCell } from './TableCell.vue'
export { default as TableCaption } from './TableCaption.vue'